openapi: 3.0.3
info:
  version: 1.0.0
  title: Sky Test App with Spring Boot
  contact:
    email: sergendorfin@gmail.com
    url: https://www.linkedin.com/in/sergii-kononenko/
  license:
    name: open
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification and my skills.
tags:
  - name: User
    description: User operations
  - name: Project
    description: Project operations
paths:
  /v1/users:
    get:
      tags:
        - User
      summary: Get a list of Users
      description: Get a list of Users
      operationId: listUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      required:
        - id
        - password
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
